//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPGYaroMoll.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public int IdArea { get; set; }
        public string NameArea { get; set; }
        public int IdAddres { get; set; }
        public int IdPerformance { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Performance Performance { get; set; }
    }
}
