//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OPGYaroMoll.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitors
    {
        public int IdVisitors { get; set; }
        public string ComleteNameVisitors { get; set; }
        public string EmailVisitors { get; set; }
        public string NumberPhoneVisitors { get; set; }
        public int IdTicket { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
